### ISSUE TITLE
Create a sample REST settings yml

### ISSUE THREAD

**Issue by ericpugh** [ericpugh/drupal-content-direct#2]
Create a sample yml file with the REST settings required by Content Direct
For example:

```
resources:
  entity:node:
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
    POST:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
```
